apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: BackstageGoLangTemplate
  description: BackstageGoLangTemplate
  annotations: 
    github.com/project-slug: hemantbhosale916/BackstageGoLangTemplate
    backstage.io/source-ref: "https://github.com/hemantbhosale916/BackstageGoLangTemplate"
    backstage.io/techdocs-ref: url:https://github.com/hemantbhosale916/BackstageGoLangTemplate
    backstage.io/github-actions-id: https://github.com/hemantbhosale916/BackstageGoLangTemplate
spec:
  type: service
  lifecycle: experimental
  owner: hemantbhosale916
